"""Top-level C++ code generator orchestration."""

from importlib import import_module
from collections.abc import Iterable
from typing import Protocol, cast


class _MessageDescriptor(Protocol):
    name: str


class _MessageGenerator(Protocol):
    def generate_declaration(self) -> str: ...

    def generate_implementation(self) -> str: ...


class _MessageGeneratorCtor(Protocol):
    def __call__(self, message: _MessageDescriptor) -> _MessageGenerator: ...


class _FileDescriptor(Protocol):
    name: str
    package: str
    dependency: Iterable[str]
    message_type: Iterable[_MessageDescriptor]


class CppGenerator:
    def __init__(self, proto_file: _FileDescriptor, parameter: str) -> None:
        self.proto_file: _FileDescriptor = proto_file
        self.parameter: str = parameter
        # Keep the plural alias for compatibility with existing callers/tests.
        self.parameters: str = parameter
        self.namespace: str = self._get_namespace()

    def generate_header(self) -> str:
        """Generate the .pb.h file content."""
        parts: list[str] = []
        parts.append(self._generate_header_preamble())
        parts.append(self._generate_includes())
        parts.append(self._generate_namespace_open())
        parts.append(self._generate_forward_declarations())

        message_generator_cls = self._get_message_generator_cls()
        for message in self.proto_file.message_type:
            mg = message_generator_cls(message)
            parts.append(mg.generate_declaration())

        parts.append(self._generate_namespace_close())
        parts.append(self._generate_header_postamble())

        return self._join_parts(parts)

    def generate_source(self) -> str:
        """Generate the .pb.cc file content."""
        parts: list[str] = []
        parts.append(self._generate_source_preamble())
        parts.append(self._generate_includes())
        parts.append(self._generate_namespace_open())

        message_generator_cls = self._get_message_generator_cls()
        for message in self.proto_file.message_type:
            mg = message_generator_cls(message)
            parts.append(mg.generate_implementation())

        parts.append(self._generate_namespace_close())

        return self._join_parts(parts)

    def _join_parts(self, parts: Iterable[str]) -> str:
        return "\n\n".join(part for part in parts if part)

    def _get_message_generator_cls(self) -> _MessageGeneratorCtor:
        try:
            module = import_module(".message_generator", package=__package__)
        except ImportError:
            module = import_module("message_generator")
        return cast(_MessageGeneratorCtor, getattr(module, "MessageGenerator"))

    def _get_namespace(self) -> str:
        if self.proto_file.package:
            return self.proto_file.package.replace(".", "::")
        return ""

    def _generate_namespace_open(self) -> str:
        if self.namespace:
            parts = self.namespace.split("::")
            return "\n".join([f"namespace {part} {{" for part in parts])
        return ""

    def _generate_namespace_close(self) -> str:
        if self.namespace:
            parts = self.namespace.split("::")
            return "\n".join([f"}}  // namespace {part}" for part in reversed(parts)])
        return ""

    def _generate_header_guard(self) -> str:
        name = self.proto_file.name.upper().replace(".", "_").replace("/", "_")
        return f"PROTOOPT_GENERATED_{name}_"

    def _generate_header_preamble(self) -> str:
        header_guard = self._generate_header_guard()
        return (
            "// Generated by protoc-gen-cpp-opt. DO NOT EDIT!\n"
            f"// Source: {self.proto_file.name}\n\n"
            f"#ifndef {header_guard}\n"
            f"#define {header_guard}\n\n"
            "#include <cstdint>\n"
            "#include <string>\n"
            '#include "google/protobuf/message.h"\n'
            '#include "google/protobuf/arena.h"\n'
            '#include "protoopt/arena_string.h"\n'
            '#include "protoopt/lazy_field.h"\n'
            '#include "protoopt/unknown_field_skipper.h"'
        )

    def _generate_header_postamble(self) -> str:
        return f"#endif  // {self._generate_header_guard()}"

    def _generate_source_preamble(self) -> str:
        header_file = self.proto_file.name.replace(".proto", ".pb.h")
        return (
            "// Generated by protoc-gen-cpp-opt. DO NOT EDIT!\n"
            f"// Source: {self.proto_file.name}\n\n"
            f'#include "{header_file}"\n'
            '#include "google/protobuf/wire_format.h"\n'
            '#include "google/protobuf/io/coded_stream.h"'
        )

    def _generate_includes(self) -> str:
        includes: list[str] = []
        for dependency in self.proto_file.dependency:
            if dependency.endswith(".proto"):
                includes.append(f'#include "{dependency[:-6]}.pb.h"')
            else:
                includes.append(f'#include "{dependency}"')
        return "\n".join(includes)

    def _generate_forward_declarations(self) -> str:
        if not self.proto_file.message_type:
            return ""

        lines = ["// Forward declarations"]
        for message in self.proto_file.message_type:
            lines.append(f"class {message.name};")
        return "\n".join(lines)
